### PR TITLE
Refactoring for cleaner interfaces in spark

### PR DESCRIPTION
**Pull request by nkronenfeld**
Three main changes:

1. Convenience classes and implicits for constructing logs from a spark session or context
2. Using apache logging to log the actual messages, so that it plays nicely with existing logging
3. Cleaning up tests, getting rid of extraneous usages of docker that add nothing but complications

### CODE REVIEW

**Comment by nkronenfeld** [comment]
One down-side to this... I tried getting rid of existing appenders during testing, but adding them back in at the end of tests caused problems, so for the moment, they are left out.  There's a commented-out line that removes them, drastically reducing the amount of test spam.

**Comment by nkronenfeld** [comment]
Build is failing because it uses some build tasks that were no longer needed.  Just running gradlew test works fine now without a separate env

**Comment by nkronenfeld** [comment]
If you're uncomfortable with testing spark without docker, see https://github.com/nkronenfeld/spark-test
It all works just fine, checks for serializability of classes and everything.

**Comment by Ghnuberath** [comment]
Please split test harness change from your actual change. I'm okay with debating the harness change for local development purposes, but would strongly prefer retaining the harness in the CI system (i.e. two different gradle tasks).

This is a library that involves socket communication between workers and a driver. There's no integration test if it is tested without actual workers, a driver, and a real network.

**Pull request closed without merging**
